services:
  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: resource-db
      POSTGRES_USER: user8080
      POSTGRES_PASSWORD: password8080
    ports:
      - "5432:5432"

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: song-db
      POSTGRES_USER: user8082
      POSTGRES_PASSWORD: password8082
    ports:
      - "5433:5432"
