# Build stage
FROM maven:3.9.9-eclipse-temurin-17-alpine AS build
WORKDIR /app

# Copy parent POM and install dependencies
COPY pom.xml /app/

# Copy entire application to Docker
COPY . /app

RUN mvn install -DskipTests

# Cache Maven dependencies
COPY resource-service/pom.xml ./resource-service/
RUN mvn -f ./resource-service/pom.xml dependency:go-offline

# Copy source code and build package
COPY resource-service/src ./resource-service/src
RUN mvn -f ./resource-service/pom.xml clean package -DskipTests

# Production stage
FROM eclipse-temurin:17-jre-alpine-3.21
WORKDIR /app

# Copy the built jar file
COPY --from=build /app/resource-service/target/*.jar ./app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]