spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/song-db
    driverClassName: org.postgresql.Driver
    username: user8082
    password: password8082

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8082
  servlet:
    context-path: /song-service

resource-service:
  baseUrl: ${RESOURCE_SERVICE_URL:http://localhost:8080}/resource-service/api/v1/resources/
