spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  datasource:
    url: jdbc:postgresql://localhost:5432/resource-db
    driverClassName: org.postgresql.Driver
    username: user8080
    password: password8080

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
  servlet:
    context-path: /resource-service

song-service:
  baseUrl: http://localhost:8082/song-service/api/v1/songs
